OLED_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
# REPEAT_KEY_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
MOUSEKEY_ENABLE = yes

SRC += features/achordion.c
SRC += features/layer_lock.c

